# WILL UPDATE THIS FILE LATER. THIS IS JUST A PLACEHOLDER FOR NOW.
name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Deploy to Heroku
        env:
          VPS_SECRET_KEY: ${{ secrets.VPS_SECRET_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/your-app-name.git
          git push heroku main --force
